### ISSUE TITLE
The repository URL `example-esbuild-plugin` returns 404

### ISSUE THREAD

**Issue by trivikr** [esbuild/community-plugins#71]
### Is your request related to a problem? Please describe.
The repository URL listed for `example-esbuild-plugin` in README returns 404.
https://github.com/esbuild/community-plugins/blob/1be7c0f62150cb9025cdbbdb97b9a88f0f1767f3/README.md#L101

Link: https://github.com/esbuild/example-esbuild-plugin

### Describe the solution you'd like
Provide example ESBuild plugin repository at https://github.com/esbuild/example-esbuild-plugin, or some different name under esbuild project

**Comment by trivikr** [comment]
Looking at the names of other plugins, a better name for example plugin would be `esbuild-plugin-example`

**Comment by evanw** [comment]
It's just example placeholder text. It's not supposed to exist. I can change the name since this is the second time this has come up, but I don't think it needs its own repository.
